import { ProductItem } from "../../@types/interfaces/Product";

export const PRODUCTS: ProductItem[] = [
  {
    id: "1",
    name: "Camiseta",
    brand: "Marca A",
    code: "ABC123",
    price: "29.99",
  },
  {
    id: "2",
    name: "Calça Jeans",
    brand: "Marca B",
    code: "DEF456",
    price: "49.99",
  },
  {
    id: "3",
    name: "Tênis",
    brand: "Marca C",
    code: "GHI789",
    price: "79.99",
  },
  {
    id: "4",
    name: "Jaqueta",
    brand: "Marca D",
    code: "JKL012",
    price: "99.99",
  },
  {
    id: "5",
    name: "Saia",
    brand: "Marca E",
    code: "MNO345",
    price: "39.99",
  },
  {
    id: "6",
    name: "Blusa",
    brand: "Marca F",
    code: "PQR678",
    price: "19.99",
  },
  {
    id: "7",
    name: "Shorts",
    brand: "Marca G",
    code: "STU901",
    price: "34.99",
  },
  {
    id: "8",
    name: "Vestido",
    brand: "Marca H",
    code: "VWX234",
    price: "59.99",
  },
  {
    id: "9",
    name: "Sapato",
    brand: "Marca I",
    code: "YZA567",
    price: "89.99",
  },
  {
    id: "10",
    name: "Cinto",
    brand: "Marca J",
    code: "BCD890",
    price: "14.99",
  },
  {
    id: "11",
    name: "Blazer",
    brand: "Marca K",
    code: "EFG123",
    price: "74.99",
  },
  {
    id: "12",
    name: "Sandália",
    brand: "Marca L",
    code: "HIJ456",
    price: "49.99",
  },
  {
    id: "13",
    name: "Bermuda",
    brand: "Marca M",
    code: "KLM789",
    price: "24.99",
  },
  {
    id: "14",
    name: "Casaco",
    brand: "Marca N",
    code: "OPQ012",
    price: "89.99",
  },
  {
    id: "15",
    name: "Meia",
    brand: "Marca O",
    code: "RST345",
    price: "9.99",
  },
  {
    id: "16",
    name: "Luva",
    brand: "Marca P",
    code: "UVW678",
    price: "7.99",
  },
  {
    id: "17",
    name: "Boné",
    brand: "Marca Q",
    code: "XYZ901",
    price: "12.99",
  },
  {
    id: "18",
    name: "Pulseira",
    brand: "Marca R",
    code: "ABC234",
    price: "4.99",
  },
  {
    id: "19",
    name: "Colar",
    brand: "Marca S",
    code: "DEF567",
    price: "14.99",
  },
  {
    id: "20",
    name: "Anel",
    brand: "Marca T",
    code: "GHI890",
    price: "19.99",
  },
];
